workout/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workoutnotes.urls')),
]

workoutnotes/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from .views import HomeView, SignupView, WorkoutListView, AddExerciseView, workout_detail_view, new_workout_view, edit_workout_view, start_workout, stop_workout, cancel_workout, save_workout, add_exercise_to_workout, save_routine, load_routine

app_name = "workoutnotes"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("new-workout/", new_workout_view),
    path("edit-workout/<int:workout_id>/", edit_workout_view),
    path("all/", WorkoutListView.as_view(), name="workout_list"),
    path("workouts/<int:workout_id>/", workout_detail_view),
    path("cancel-workout/<int:workout_id>/", cancel_workout),
    path("start-workout/<int:workout_id>/", start_workout),
    path("stop-workout/<int:workout_id>/", stop_workout),
    path("save-workout/<int:workout_id>/", save_workout),
    path("add-exercise/<int:workout_id>/", add_exercise_to_workout),
    path("save-routine/<int:workout_id>/", save_routine),
    path("load-routine/<int:workout_id>/", load_routine),
]

workoutnotes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField

class Workout(models.Model):
    name = models.TextField(default='My workout')
    start_time = models.DateTimeField(blank=True, null=True)
    finish_time = models.DateTimeField(blank=True, null=True)
    duration = models.DurationField(blank=True, null=True)
    routine = models.ForeignKey('Routine', null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='workouts')
    notes = models.CharField(max_length=1024, blank=True, null=True)
    def __str__(self):
        return self.name

class Exercise(models.Model):
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=100)
    sets = models.PositiveIntegerField()
    repsss = models.JSONField(blank=True, default={"1": 0})
    weight = models.PositiveIntegerField()
    performed = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Routine(models.Model):
    name = models.TextField()
    exercises = models.JSONField()

    def __str__(self):
        return self.name

workoutnotes/views.py
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from  django.views.generic.detail import DetailView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from .models import Exercise, Workout, Routine
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.db.models import Sum

class SignupView(FormView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('workoutnotes:home')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'workoutnotes/home.html'
    model = User
    context_object_name = 'user'

class WorkoutListView(LoginRequiredMixin, ListView):
    template_name = 'workoutnotes/workout_list.html'
    model = Workout
    context_object_name = 'workouts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workouts'] = Workout.objects.filter(user=self.request.user)
        return context



def workout_detail_view(request, workout_id):
    workout = Workout.objects.get(id=workout_id, user=request.user)
    exercises = Exercise.objects.filter(workout=workout)
    return render(
        request, 
        'workoutnotes/workout_detail.html', 
        {'workout': workout, 'exercises': exercises}
        )

def new_workout_view(request):
    new_workout = Workout()
    new_workout.user = request.user
    new_workout.save()
    return HttpResponseRedirect(f'/edit-workout/{new_workout.id}/')

def edit_workout_view(request, workout_id):
    workout = Workout.objects.get(id=workout_id, user=request.user)
    exercises = Exercise.objects.filter(workout=workout)
    routines = Routine.objects.all()
    return render(
        request, 
        'workoutnotes/edit_workout.html', 
        {'workout': workout, 'exercises': exercises, 'routines': routines}
        )

def start_workout(request, workout_id):
    workout = Workout.objects.get(id=workout_id, user=request.user)
    workout.start_time = timezone.now()
    workout.save()
    return HttpResponseRedirect(f'/edit-workout/{workout_id}/')

def stop_workout(request, workout_id):
    workout = Workout.objects.get(id=workout_id, user=request.user)
    workout.finish_time = timezone.now()
    workout.duration = workout.finish_time - workout.start_time
    workout.save()

    exercises = Exercise.objects.filter(workout=workout)
    i = 0
    for exercise in exercises:
        exercise.name = request.POST[f'name_{exercise.id}']
        exercise.weight = request.POST[f'weight_{exercise.id}']
        for s in exercise.repsss:
            exercise.repsss[s] = request.POST[f'rep_{s}']
            i += 1

        exercise.save()
    return HttpResponseRedirect(f'/edit-workout/{workout_id}/')

def save_workout(request, workout_id):
    workout = Workout.objects.get(id=workout_id, user=request.user)
    workout.name = request.POST['name']
    workout.notes = request.POST['notes']
    workout.save()

    if workout.routine:
        routine = workout.routine
        routine = workout_to_routine(workout_id, routine)
        routine.save()

    return HttpResponseRedirect(f'/workouts/{workout_id}/')

def delete_workout(request, workout_id):
    workout = Workout.objects.get(id=workout_id, user=request.user)
    workout.delete()
    return HttpResponseRedirect('/all/')

def cancel_workout(request, workout_id):
    return delete_workout(request, workout_id)

def add_exercise_to_workout(request, workout_id):
    workout = Workout.objects.get(id=workout_id, user=request.user)
    exercise = Exercise()

    exercise.workout = workout
    exercise.name = request.POST['name']
    exercise.weight = request.POST['weight']
    exercise.sets = request.POST['sets']
    reps = int(request.POST['reps'])
    exercise.repsss = dict()
    exercise.created_by = request.user
    
    cur_workout_exercises = Exercise.objects.filter(workout__id=workout_id)
    sets_num = cur_workout_exercises.aggregate(Sum('sets'))['sets__sum']
    sets_num = sets_num if sets_num else 0
    for i in range(sets_num, sets_num+int(exercise.sets)):
        exercise.repsss[i] = reps
    exercise.save()

    return HttpResponseRedirect(f'/edit-workout/{workout_id}/')
class AddExerciseView(CreateView):
    model = Exercise
    fields = ['name', 'weight', 'sets']
    template_name = 'workoutnotes/add_exercise.html'
    success_utl = reverse_lazy('workounotes:edi-workout')

    def form_valid(self, form):
        form.instance.workout = Workout.objects.get(id=self.kwargs['workout_id'])
        return super().form_valid(form)

def save_routine(request, workout_id):
    routine = Routine()
    routine.name = request.POST['name']
    workout = Workout.objects.get(id=workout_id)
    workout.routine = routine

    routine = workout_to_routine(workout_id, routine)

    routine.save()
    workout.save()

    return HttpResponseRedirect(f'/edit-workout/{workout_id}/')
    
def load_routine(request, workout_id):
    workout = Workout.objects.get(id=workout_id)
    routine_id = request.POST['selected_routine_id']
    routine = Routine.objects.get(id=routine_id)
    workout.routine = routine
    workout.save()


    for routine_exercise in routine.exercises:
        new_exercise = Exercise()
        new_exercise.workout = workout
        new_exercise.name = routine_exercise['name']
        new_exercise.weight = routine_exercise['weight']
        new_exercise.sets = routine_exercise['sets']
        new_exercise.repsss = routine_exercise['reps']
        new_exercise.created_by = request.user
        new_exercise.save()

    return HttpResponseRedirect(f'/edit-workout/{workout_id}/')   
##################################################

def workout_to_routine(workout_id, routine):
    exercises = Exercise.objects.filter(workout__id=workout_id)
    routine_table = []
    
    for exercise in exercises:
        routine_table.append(
            {
                'name': exercise.name,
                'weight': exercise.weight,
                'sets': exercise.sets,
                'reps': exercise.repsss
            }
        )

    routine.exercises = routine_table

    return routine
class ExerciseCreateView(CreateView):
    model = Exercise
    fields = ['name', 'sets', 'reps', 'weight']
    success_url = reverse_lazy('workoutnotes:home')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class ExerciseDetailView(DetailView):
    model = Exercise
    context_object_name = 'exercise'

class ExerciseUpdateView(UpdateView):
    model = Exercise
    fields = ['name', 'sets', 'reps', 'weight']
    context_object_name = 'exercise'

    def get_success_url(self) -> str:
        return reverse_lazy('workoutnotes:exercise_detail', kwargs={'pk': self.object.pk})
    
    def test_func(self):
        exercise = self.get_object()
        return self.request.user == exercise.created_by

class ExerciseDeleteView(DeleteView):
    model = Exercise
    success_url = reverse_lazy('workoutnotes:exercises_list')

    def test_func(self):
        exercise = self.get_object()
        return self.request.user == exercise.created_by

workoutnotes/templates/workoutnotes/add_exercise.html
{% extends 'workoutnotes/edit_workout.html' %}

{% block 'add' %}
    <h3>Exercise Form</h3>
    <form method = "POST" action = "">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value = "Submit">
    </form>
{% endblock %}

workoutnotes/templates/workoutnotes/edit_workout.html
<html>
    <head>
        <title>Workout Tracker</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>

        <div class="wrapper">
            <header>
                <h1>Weight Training Tracker</h1>
            </header>

            <section>

                <ul class="training_times">
                    {% if exercises %}

                        {% if workout.start_time %}
                            <!-- straining started - show start -->
                            <li><b>Start:</b> {{ workout.start_time|date:'H:i' }}</li>

                            {% if workout.finish_time %}
                                <!-- training is over - show end time -->
                                <li><b>End:</b> {{ workout.finish_time|date:'H:i' }}</li>
                                <li><b>Duration:</b> {{ workout.duration }}</li>
                            {% endif %}

                        {% endif %}

                    {% endif %}
                </ul>

                <div class="exercises_form">
                    {% if exercises %}
                    <form action="/stop-workout/{{workout.id}}/" method="POST">{% csrf_token %}
                        <!-- training started - show stop button -->
                        
                            <!-- show labels for exercises -->
                            <div class="labels_row"> 
                                <div class="exercises_label name_fields">Exercise name</div>
                                <div class="exercises_label number_input">Weight</div>
                                <div class="exercises_label number_input">Sets</div>
                            </div>


                            <!-- show exercises -->
                            {% for exercise in exercises %}
                                
                                <div class="exercise_row">

                                    <div class="form_input">
                                        <input type="text" class="name_fields" name="name_{{exercise.id}}" value="{{exercise.name}}" readonly/>
                                    </div>

                                    <div class="form_input">
                                        <input type="number" class="number_input" name="weight_{{exercise.id}}" min="0" step="0.1" value="{{exercise.weight}}"/>
                                    </div>

                                    {% for i, j in exercise.repsss.items %}
                                        <div class="form_input">
                                            <input type="number" class="number_input" name="rep_{{i}}" value="{{j}}" min="0" step="1"/>
                                        </div>
                                    {% endfor %}

                                </div>
                                
                            {% endfor %}
                            
                            {% if workout.start_time and not workout.finish_time %}
                                <br />
                                <div class="control_buttons">
                                    <div class="form_input">    
                                        <input type="submit" class="stop" value="Stop"/>
                                    </div>
                                </div>
                            {% endif %}
                    </form>
                    

                        <!-- training have not started yet - start button -->
                        {% if not workout.start_time %}
                            <div class="control_buttons">
                                <div class="form_input">  
                                    <form action="/start-workout/{{workout.id}}/" method="POST">{% csrf_token %}  
                                        <input type="submit" class="start" value="Start"/>
                                    </form>
                                </div>
                                <!-- training can be canceled at any point -->
                                
                            </div>
                        {% endif %}


                        
                        <!-- training can be saved only if it started and finished -->
                        {% if workout.start_time and workout.finish_time %}
                            <form action="/save-workout/{{workout.id}}/" method="POST">{% csrf_token %}
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label">Workout Name</label>
                                    <input type="text" class="form-control" name = "name" id="exampleFormControlInput1" placeholder="My workout">
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlTextarea1" class="form-label">Notes</label>
                                    <textarea class="form-control" name = "notes" id="exampleFormControlTextarea1" rows="3"></textarea>
                                </div>
                                <div class="form_input">
                                    <input type="submit" id="save_training" value="Save"/>
                                </div>
                            </form>
                        {% endif %}
                    {% else %}
                        <p class="div_label">So empty! Add some exercises to the training!</p>
                    {% endif %}<!-- exercises -->
                </div>


                <!-- Add exercise form -->             
                {% if not workout.start_time and not workout.routine %}
                    <br />
                    <div class="add_form">
                        <p class="div_label">Add exercise to the training</p>
                        <form action="/add-exercise/{{workout.id}}/" method="POST">{% csrf_token %}
                            <div class="form_input">
                                <label for="add_name">Exercise name</label><br />
                                <input type="text" class="name_fields" id="add_name" name="name" value="Exercise"/>
                            </div>

                            <div class="form_input">
                                <label for="add_weight">Weight</label><br />
                                <input type="number" id="add_weight" class="number_input" name="weight" min="0" value="0.0" step="0.1"/>
                            </div>


                            <div class="form_input">
                                <label for="add_sets">Sets</label><br />
                                <input type="number" class="number_input" id="add_sets" name="sets" value="3" step="1" min="1" max="6">
                            </div>

                            <div class="form_input">
                                <label for="add_reps">Reps</label><br />
                                <input type="number" class="number_input" id="add_reps" name="reps" value="0" step="1" min="1" max="1000">
                            </div>

                            <div class="form_input">
                                <label for="add_submit">&nbsp;</label><br />
                                <input type="submit" id="add_submit" value="Add"/>
                            </div>
                        </form>
                    </div>

                    {% if exercises %}
                        <div class="add_form">
                            <p class="div_label">Save as workout routine</p>
                            <!-- show save as training plan form -->
                            <form action="/save-routine/{{workout.id}}/" method="POST">{% csrf_token %}
                                <div class="form_input">
                                    <label for="plan_name">Workout routine name</label><br />
                                    <input type="text" class="input_wide" id="plan_name" name="name" value="My workout routine"/>
                                </div>

                                <div class="form_input">
                                    <label for="save_plan">&nbsp;</label><br />
                                    <input type="submit" id="save_plan" value="Save"/>
                                </div>
                            </form>
                        </div>
                    {% elif routines %}
                        <div class="add_form">
                            <!-- show load as training plan form -->
                            <form action="/load-routine/{{workout.id}}/" method="POST">{% csrf_token %}
                                <div class="form_input">
                                    <label for="select_plan">Load training plan</label><br />
                                    <select name="selected_routine_id" class="input_wide" id="select_plan">
                                        {% for routine in routines %}
                                            <option value="{{routine.id}}">{{ routine.name }}</option>
                                        {% endfor %}
                                    </select>    
                                </div>

                                <div class="form_input">
                                    <label for="load_plan">&nbsp;</label><br />
                                    <input type="submit" id="load_plan" value="Load"/>
                                </div>
                            </form>
                        </div>
                    {% else %}
                        <!-- show nothing -->
                    {% endif %}

                {% endif %}
                
            </section>
            <div class="form_input">
                <form><button formaction="/cancel-workout/{{workout.id}}/">Cancel</button></form>
            </div>
        </div>
    </body>
</html>

workoutnotes/templates/workoutnotes/exercise_confirm_delete.html
<h1>Confirm Delete</h1>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>

workoutnotes/templates/workoutnotes/exercise_form.html
<h1>Create Exercise</h1>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Save" />
</form>

workoutnotes/templates/workoutnotes/home.html
<html>
    <head>
        <title>Workout Tracker</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>

        <div class="wrapper">
            <header>
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">Workout tracker</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                          <a class="nav-link active" aria-current="page" href="#">Home</a>
                          <a class="nav-link" href="{% url 'workoutnotes:workout_list' %}">View workouts</a>
                          <a class="nav-link" href="/new-workout/">Create workout</a>
                          <a class="nav-link" href="{% url 'workoutnotes:logout' %}">Log Out</a>
                        </div>
                      </div>
                    </div>
                  </nav>
                
            </header>
            <h1>Hello, {{user.username}}</h1>
            <section>

                {% block content %}
                {% endblock %}
                         
            </section>

        </div>
    </body>
</html>

workoutnotes/templates/workoutnotes/workout_detail.html
{% extends 'workoutnotes/home.html' %}

{% block content %}

    <div class="dropdown">
        <button class="dropdown_button">&raquo;</button>
        <div class="dropdown_content">
            <a href="/workoutnotes/edit-workout/{{workout.id}}/">Edit</a>
        </div>
    </div>

    <h1>{{ workout.name }}</h1>
    
    

    <ul class="training_times">
        <li><b>Start:</b> {{ workout.start_time|date:"m/d Y" }}</li>
        <!--<li><b>End:</b> {{ training.time_end|date:'Y-m-d H:i' }}</li>-->
        <li><b>Duration:</b> {{ workout.duration }}</li>
        <li><b>Created by:</b> {{ workout.user }}</li>
        <li><b>Notes:</b> {{ workout.notes }}</li>
    </ul>

    
    <table class="table table-bordered border-primary">
        <th>Exercise</th>
        <th colspan="2">Weight</th>
        <th colspan="8">Series</th>
        {% for exercise in exercises %}
            <tr>
                <td>{{ exercise.name }}</td>
                <td>{{ exercise.weight }} kg</td>
                {% for i, r in exercise.repsss.items %}
                    <td>{{r}}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
    

{% endblock %}


<!-- <h1>Exercise Detail</h1>
<ul>
  <li>Name: {{exercise.name}}</li>
  <li>Created: {{exercise.created|date}}</li>
  <li>Sets: {{exercise.sets}}</li>
  <li>Reps: {{ exercise.reps}}</li>
  <li>Weight: {{exercise.weight}}</li>
</ul>

{% if user == exercise.created_by %}
<a href="{% url 'workoutnotes:update_exercise' exercise.id %}">Edit</a>
<a href="{% url 'workoutnotes:delete_exercise' exercise.id %}">Delete</a>
{% endif %}
 -->

workoutnotes/templates/workoutnotes/workout_list.html
{% extends 'workoutnotes/home.html' %}

{% block content %}
    <h1>My workouts</h1>
    <table class="table table-striped table-hover">
        <th>Workout</th>
        <th>Date</th>
        <th>Duration</th>
        {% for workout in workouts %}
            <tr>
                <td><a href="/workouts/{{workout.id}}">{{workout.name}}</a></td>
                <td>{{workout.start_time|date:"m/d Y"}}</td>
                <td>{{ workout.duration}}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}